import 'package:flutter_ftv/core/domain/ids.dart';
import 'package:flutter_ftv/core/domain/result.dart';
import 'package:flutter_ftv/features/courts/domain/court.dart';
import 'package:flutter_ftv/features/courts/domain/court_status.dart';
import 'package:flutter_ftv/features/history/domain/history_event.dart';
import 'package:flutter_ftv/features/history/domain/history_event_type.dart';
import 'package:flutter_ftv/features/matches/domain/court_slot.dart';
import 'package:flutter_ftv/features/matches/domain/match.dart';
import 'package:flutter_ftv/features/matches/domain/match_status.dart';
import 'package:flutter_ftv/features/matches/domain/rotation_state.dart';
import 'package:flutter_ftv/features/pairs/domain/pair.dart';
import 'package:flutter_ftv/features/pairs/domain/pair_origin.dart';
import 'package:flutter_ftv/features/pairs/domain/pair_status.dart';
import 'package:flutter_ftv/features/players/domain/player.dart';
import 'package:flutter_ftv/features/players/domain/player_status.dart';

/// The outcome of a rotation transition.
class RotationResult {
  const RotationResult({
    required this.state,
    this.generatedEvents = const [],
    this.errors = const [],
  });

  /// A failed result: the state is returned unchanged and [error] explains why.
  factory RotationResult.failure(RotationState state, DomainError error) =>
      RotationResult(state: state, errors: [error]);

  /// The resulting state (unchanged on failure).
  final RotationState state;

  /// History events generated by this transition (also appended to
  /// [RotationState.history]).
  final List<HistoryEvent> generatedEvents;

  /// Validation errors; empty on success.
  final List<DomainError> errors;

  bool get isSuccess => errors.isEmpty;
  bool get hasErrors => errors.isNotEmpty;
}

/// Applies the futevôlei court-ladder rotation rules as pure state → state
/// transitions.
///
/// No dependency on Flutter, Drift, or Riverpod. Determinism is guaranteed by
/// injectable id builders and a caller-supplied [timestamp]; there is no hidden
/// clock or randomness.
///
/// ## Ladder model
///
/// A winning pair stays as the *home* (reigning) pair on its own court. On a
/// court below the top its status is [PairStatus.waitingForUpperCourt]: it holds
/// its court until the court immediately above frees, then rises to it. The
/// whole ladder is reconciled after every transition by [_Transaction.settleLadder]:
///
/// * risers move **up** — the reigning winner of a court rises into the court
///   directly above once that court is free (either as its lone home when the
///   court above is empty, or as the challenger when the court above holds a
///   lone reigning winner);
/// * the **top court** is fed a challenger from the individual player queue when
///   no riser is available below (this is what makes a single-court session
///   work: the reigning winner is challenged by the next pair from the queue);
/// * **empty courts** are filled from the queue — during a running session from
///   the bottom of the ladder (new entrants join low), and during initial
///   seeding ([fillCourts]) from the top.
///
/// A court is only left waiting (no challenger) when the court directly below it
/// currently has a match in progress: a genuine riser is pending. This is the
/// key rule that prevents the ladder from deadlocking.
class RotationService {
  RotationService({
    MatchId Function(int sequence)? matchIdBuilder,
    PairId Function(int sequence)? pairIdBuilder,
    HistoryEventId Function(int sequence)? eventIdBuilder,
  }) : _matchIdBuilder = matchIdBuilder ?? ((s) => MatchId('match-$s')),
       _pairIdBuilder = pairIdBuilder ?? ((s) => PairId('rpair-$s')),
       _eventIdBuilder = eventIdBuilder ?? ((s) => HistoryEventId('evt-$s'));

  final MatchId Function(int sequence) _matchIdBuilder;
  final PairId Function(int sequence) _pairIdBuilder;
  final HistoryEventId Function(int sequence) _eventIdBuilder;

  /// Finalizes the match [matchId], recording [winnerPairId] as the winner, and
  /// applies the full rotation sequence atomically:
  /// record result → dissolve losing pair → return losers individually to the
  /// end of the queue → keep the winner (unless it is a manual pair, which is
  /// dissolved after its one cycle) → reconcile the ladder → record history.
  ///
  /// * [winnerGotTired] dissolves the winning pair too; all four players return
  ///   individually to the queue.
  /// * [bothPairsLeft] dissolves both pairs; all four players return.
  ///
  /// [timestamp] stamps every generated [HistoryEvent] so the transition stays
  /// deterministic.
  RotationResult finishMatch({
    required RotationState state,
    required MatchId matchId,
    required PairId winnerPairId,
    bool winnerGotTired = false,
    bool bothPairsLeft = false,
    required DateTime timestamp,
  }) {
    final match = state.matchById(matchId);
    if (match == null) {
      return RotationResult.failure(
        state,
        DomainError('match_not_found', 'Match ${matchId.value} does not exist'),
      );
    }
    if (match.status != MatchStatus.active) {
      return RotationResult.failure(
        state,
        DomainError('match_not_active', 'Match ${matchId.value} is not active'),
      );
    }
    if (!match.contains(winnerPairId)) {
      return RotationResult.failure(
        state,
        DomainError(
          'winner_not_in_match',
          'Pair ${winnerPairId.value} is not part of match ${matchId.value}',
        ),
      );
    }

    final tx = _Transaction(
      state: state,
      timestamp: timestamp,
      matchIdBuilder: _matchIdBuilder,
      pairIdBuilder: _pairIdBuilder,
      eventIdBuilder: _eventIdBuilder,
    );

    final loserPairId = match.opponentOf(winnerPairId)!;
    final courtId = match.courtId;
    final court = state.courtById(courtId)!;

    // 1. Record the result.
    tx.finalizeMatch(
      match,
      winnerPairId: winnerPairId,
      loserPairId: loserPairId,
    );

    // 2-4. Dissolve pairs and return players individually to the queue.
    Pair? survivingWinner;
    if (bothPairsLeft) {
      tx.event(HistoryEventType.bothPairsLeft, 'Both pairs left ${court.name}');
      tx.dissolveAndReturn(winnerPairId);
      tx.dissolveAndReturn(loserPairId);
    } else if (winnerGotTired) {
      tx.event(
        HistoryEventType.winnerTired,
        'Winning pair tired on ${court.name}',
      );
      tx.dissolveAndReturn(loserPairId);
      tx.dissolveAndReturn(winnerPairId);
    } else {
      tx.dissolveAndReturn(loserPairId);
      final winner = tx.pair(winnerPairId);
      // A manually chosen pair lasts only one cycle: once it stops winning — or
      // here, even on a win — it does not defend again. It is dissolved and its
      // players return individually to the queue.
      if (winner != null && winner.origin == PairOrigin.manual) {
        tx.dissolveAndReturn(winnerPairId);
      } else {
        survivingWinner = winner;
      }
    }

    // 5. Place the surviving winner as the reigning home pair, or clear court.
    if (survivingWinner != null) {
      tx.setHomeReigning(courtId, winnerPairId, court.level);
    } else {
      tx.clearCourt(courtId);
    }

    // 6-7. Reconcile the ladder: promote risers upward and fill open courts
    //      (bottom-first, so new entrants join the lowest court).
    tx.settleLadder();

    // 8. Record that a rotation was applied.
    tx.event(
      HistoryEventType.rotationApplied,
      'Rotation applied on ${court.name}',
    );

    return RotationResult(state: tx.build(), generatedEvents: tx.events);
  }

  /// Fills open courts from the existing pairs / individual player queue and
  /// reconciles the ladder. Existing [PairStatus.queued] pairs are consumed in
  /// ascending `queueOrder` (so a manual pair placed at the end enters last),
  /// then new pairs are formed from the individual player queue. Occupied courts
  /// are never disturbed ([_Transaction.settleLadder] is idempotent and skips
  /// courts with a match in progress).
  ///
  /// When [fromTop] is true (default) open courts fill from the top of the
  /// ladder first (Court A before B...) — used to *start* a round after pairs
  /// have been formed. When false, open courts fill from the bottom so late
  /// entrants join the lowest court — used to seat players added while the
  /// session is already running.
  RotationResult fillCourts({
    required RotationState state,
    required DateTime timestamp,
    bool fromTop = true,
  }) {
    final tx = _Transaction(
      state: state,
      timestamp: timestamp,
      matchIdBuilder: _matchIdBuilder,
      pairIdBuilder: _pairIdBuilder,
      eventIdBuilder: _eventIdBuilder,
    );

    tx.settleLadder(fillTopFirst: fromTop);
    tx.event(HistoryEventType.rotationApplied, 'Courts filled');

    return RotationResult(state: tx.build(), generatedEvents: tx.events);
  }

  /// Detaches [playerId] from the court they are playing on (if any): the match
  /// is voided, the player's pair is dissolved (the partner returns individually
  /// to the queue), the *opponent* pair keeps the court as its reigning home,
  /// and the ladder is reconciled. Used when the organizer removes a player who
  /// is currently on a court, so no dissolved pair or removed player is left
  /// active. Returns the state unchanged (no events) when the player is not on
  /// a court.
  ///
  /// The caller is expected to have already marked the player removed (so the
  /// removed player is not returned to the queue).
  RotationResult detachActivePlayer({
    required RotationState state,
    required PlayerId playerId,
    required DateTime timestamp,
  }) {
    // Find the active pair (referenced by a court slot) containing the player.
    for (final slot in state.slots) {
      final leaving = slot.pairIds.firstWhere(
        (id) => state.pairById(id)?.contains(playerId) ?? false,
        orElse: () => const PairId(''),
      );
      if (leaving.value.isEmpty) continue;

      final tx = _Transaction(
        state: state,
        timestamp: timestamp,
        matchIdBuilder: _matchIdBuilder,
        pairIdBuilder: _pairIdBuilder,
        eventIdBuilder: _eventIdBuilder,
      );

      // If the pair was in an active match, void it.
      if (slot.matchId != null) {
        tx.voidMatch(slot.matchId!);
      }
      // The opponent (if any) keeps the court as reigning home.
      final opponents = slot.pairIds.where((id) => id != leaving).toList();
      tx.dissolveAndReturn(leaving);
      if (opponents.isNotEmpty) {
        final level = state.courtById(slot.courtId)?.level ?? 1;
        tx.setHomeReigning(slot.courtId, opponents.first, level);
      } else {
        tx.clearCourt(slot.courtId);
      }
      tx.settleLadder();
      tx.event(
        HistoryEventType.rotationApplied,
        'Player ${playerId.value} removed from court',
      );
      return RotationResult(state: tx.build(), generatedEvents: tx.events);
    }
    return RotationResult(state: state);
  }
}

/// Internal mutable working set for a single [RotationService] transition.
///
/// Keeps everything editable via maps/lists, then rebuilds an immutable
/// [RotationState] in [build].
class _Transaction {
  _Transaction({
    required this.state,
    required this.timestamp,
    required this.matchIdBuilder,
    required this.pairIdBuilder,
    required this.eventIdBuilder,
  }) : _matchSeq = state.matches.length,
       _pairSeq = state.pairs.length,
       _eventSeq = state.history.length {
    for (final p in state.roster) {
      _roster[p.id.value] = p;
    }
    for (final p in state.pairs) {
      _pairs[p.id.value] = p;
    }
    for (final s in state.slots) {
      _slots[s.courtId.value] = s;
    }
    _queue = List<PlayerId>.of(state.queue);
    _matches = List<Match>.of(state.matches);
    _events = <HistoryEvent>[];
    _topLevel = state.courts.isEmpty
        ? 1
        : state.courts.map((c) => c.level).reduce((a, b) => a < b ? a : b);
  }

  final RotationState state;
  final DateTime timestamp;
  final MatchId Function(int) matchIdBuilder;
  final PairId Function(int) pairIdBuilder;
  final HistoryEventId Function(int) eventIdBuilder;

  final Map<String, Player> _roster = {};
  final Map<String, Pair> _pairs = {};
  final Map<String, CourtSlot> _slots = {};
  late final List<PlayerId> _queue;
  late final List<Match> _matches;
  late final List<HistoryEvent> _events;
  late final int _topLevel;

  int _matchSeq;
  int _pairSeq;
  int _eventSeq;

  List<HistoryEvent> get events => List.unmodifiable(_events);

  Pair? pair(PairId id) => _pairs[id.value];

  // --- Event helper ----------------------------------------------------------

  void event(HistoryEventType type, String description) {
    _events.add(
      HistoryEvent(
        id: eventIdBuilder(_eventSeq++),
        sessionId: state.session.id,
        type: type,
        description: description,
        createdAt: timestamp,
      ),
    );
  }

  // --- Match / pair mutations ------------------------------------------------

  void finalizeMatch(
    Match match, {
    required PairId winnerPairId,
    required PairId loserPairId,
  }) {
    final finished = match.copyWith(
      winnerPairId: winnerPairId,
      loserPairId: loserPairId,
      status: MatchStatus.finished,
    );
    final index = _matches.indexWhere((m) => m.id == match.id);
    if (index >= 0) _matches[index] = finished;
    event(HistoryEventType.matchFinished, 'Match ${match.id.value} finished');
  }

  /// Marks an in-progress match cancelled (used when a player is removed from a
  /// court mid-match); the match keeps no winner/loser.
  void voidMatch(MatchId matchId) {
    final index = _matches.indexWhere((m) => m.id == matchId);
    if (index < 0) return;
    _matches[index] = _matches[index].copyWith(status: MatchStatus.cancelled);
  }

  /// Dissolves [pairId] and returns both of its players individually to the end
  /// of the queue. The dissolved pair is kept (with [PairStatus.dissolved]) so
  /// finished matches that reference it still resolve after a reload.
  void dissolveAndReturn(PairId pairId) {
    final pair = _pairs[pairId.value];
    if (pair == null || pair.status == PairStatus.dissolved) return;
    _pairs[pairId.value] = pair.copyWith(status: PairStatus.dissolved);
    event(HistoryEventType.pairDissolved, 'Pair ${pairId.value} dissolved');
    for (final playerId in pair.playerIds) {
      _returnPlayerToEnd(playerId);
    }
  }

  void _returnPlayerToEnd(PlayerId playerId) {
    final player = _roster[playerId.value];
    // A removed player never returns to the queue.
    if (player != null && player.status == PlayerStatus.removed) return;
    if (player != null) {
      _roster[playerId.value] = player.copyWith(status: PlayerStatus.queued);
    }
    _queue.removeWhere((id) => id == playerId); // avoid duplicates
    _queue.add(playerId);
    event(
      HistoryEventType.playerReturnedToQueue,
      'Player ${playerId.value} returned to queue',
    );
  }

  // --- Court slot mutations --------------------------------------------------

  void setHomeReigning(CourtId courtId, PairId pairId, int level) {
    _slots[courtId.value] = CourtSlot(courtId: courtId, homePairId: pairId);
    _setPairStatus(pairId, _homeStatus(level));
  }

  void clearCourt(CourtId courtId) {
    _slots[courtId.value] = CourtSlot.empty(courtId);
  }

  // --- Ladder reconciliation -------------------------------------------------

  /// Reconciles the whole ladder to a stable state: promotes reigning winners
  /// up the ladder and fills open courts from the queue. Idempotent — running
  /// it again on a settled state changes nothing.
  ///
  /// When [fillTopFirst] is true (initial seeding) open courts are filled from
  /// the top of the ladder; otherwise (a running session) they fill from the
  /// bottom so new entrants join the lowest court.
  void settleLadder({bool fillTopFirst = false}) {
    final topDown = [...state.courts]
      ..sort((a, b) => a.level.compareTo(b.level));

    // A generous cap purely as an infinite-loop backstop; each iteration that
    // sets `changed` strictly consumes a queue pair or moves a pair upward, so
    // the fixpoint is reached well within this bound.
    final maxIterations = state.courts.length * 4 + state.queue.length + 4;
    var iterations = 0;
    var changed = true;
    while (changed && iterations++ < maxIterations) {
      changed = false;

      // Phase 1 — promotion, top → bottom: pull ready risers up.
      for (final court in topDown) {
        final slot = _slots[court.id.value]!;
        if (slot.hasActiveMatch) continue;
        if (slot.isEmpty) {
          final riser = _takeReadyWinnerBelow(court.level);
          if (riser != null) {
            setHomeReigning(court.id, riser, court.level);
            changed = true;
          }
        } else if (slot.awaitingChallenger) {
          final riser = _takeReadyWinnerBelow(court.level);
          if (riser != null) {
            _startMatch(
              court,
              homePairId: slot.homePairId!,
              challengerPairId: riser,
            );
            changed = true;
          }
        }
      }
      if (changed) continue;

      // Phase 2 — fill from the queue.
      final fillOrder = fillTopFirst ? topDown : topDown.reversed;
      for (final court in fillOrder) {
        final slot = _slots[court.id.value]!;
        if (slot.hasActiveMatch) continue;
        if (slot.isEmpty) {
          final home = _nextPairForCourt();
          if (home == null) continue;
          setHomeReigning(court.id, home, court.level);
          final challenger = _nextPairForCourt();
          if (challenger != null) {
            _startMatch(court, homePairId: home, challengerPairId: challenger);
          }
          changed = true;
          break;
        } else if (slot.awaitingChallenger &&
            court.level == _topLevel &&
            !_hasActiveMatchAt(court.level + 1)) {
          // The reigning winner of the top court is challenged by the next pair
          // from the queue — but only when no riser is pending from directly
          // below (the court below has no match in progress). If the court below
          // is still playing, the top court waits for that winner to rise.
          final challenger = _nextPairForCourt();
          if (challenger != null) {
            _startMatch(
              court,
              homePairId: slot.homePairId!,
              challengerPairId: challenger,
            );
            changed = true;
            break;
          }
        }
        // A non-top court holding a lone reigning winner simply waits to rise.
      }
    }
  }

  /// Whether the court at [level] exists and currently has a match in progress
  /// (a riser will eventually rise from it).
  bool _hasActiveMatchAt(int level) {
    final court = state.courtByLevel(level);
    if (court == null) return false;
    return _slots[court.id.value]?.hasActiveMatch ?? false;
  }

  /// The reigning winner of the court directly below [level] if it is ready to
  /// rise (a lone home pair, not mid-match, marked [PairStatus.waitingForUpperCourt]).
  /// On success the lower court is vacated and the pair id is returned.
  PairId? _takeReadyWinnerBelow(int level) {
    final below = state.courtByLevel(level + 1);
    if (below == null) return null;
    final belowSlot = _slots[below.id.value];
    if (belowSlot == null || !belowSlot.awaitingChallenger) return null;
    final riser = belowSlot.homePairId!;
    final pair = _pairs[riser.value];
    if (pair == null || pair.status != PairStatus.waitingForUpperCourt) {
      return null;
    }
    clearCourt(below.id);
    return riser;
  }

  /// Returns the next pair to place on a court: an unassigned [PairStatus.queued]
  /// pair (lowest `queueOrder`) if one exists, otherwise a new pair formed from
  /// the front of the individual player queue, or `null` when neither is
  /// available.
  PairId? _nextPairForCourt() => _takeQueuedPair() ?? _formPairFromQueue();

  /// Finds the next active pair with status [PairStatus.queued] that is not
  /// already assigned to a court slot. Automatic pairs are always preferred over
  /// manual ones (a manually chosen pair is penalized to the end of the pair
  /// queue and enters last, regardless of when it was created); within the same
  /// origin, the lowest `queueOrder` comes first.
  PairId? _takeQueuedPair() {
    final assigned = <String>{
      for (final slot in _slots.values)
        for (final pairId in slot.pairIds) pairId.value,
    };
    Pair? best;
    for (final pair in _pairs.values) {
      if (pair.status != PairStatus.queued) continue;
      if (assigned.contains(pair.id.value)) continue;
      if (best == null || _isEarlierInPairQueue(pair, best)) best = pair;
    }
    return best?.id;
  }

  /// Whether [candidate] should be seated before [current]: automatic origin
  /// first, then lower `queueOrder`.
  bool _isEarlierInPairQueue(Pair candidate, Pair current) {
    if (candidate.origin != current.origin) {
      return candidate.origin == PairOrigin.automatic;
    }
    return candidate.queueOrder < current.queueOrder;
  }

  void _startMatch(
    Court court, {
    required PairId homePairId,
    required PairId challengerPairId,
  }) {
    final match = Match(
      id: matchIdBuilder(_matchSeq++),
      sessionId: state.session.id,
      courtId: court.id,
      pairOneId: homePairId,
      pairTwoId: challengerPairId,
    );
    _matches.add(match);
    _slots[court.id.value] = CourtSlot(
      courtId: court.id,
      homePairId: homePairId,
      challengerPairId: challengerPairId,
      matchId: match.id,
    );
    _setPairStatus(homePairId, _homeStatus(court.level));
    _setPairStatus(challengerPairId, PairStatus.playing);
    event(
      HistoryEventType.matchStarted,
      'Match ${match.id.value} started on ${court.name}',
    );
  }

  /// Forms a pair from the two players at the front of the queue, marking them
  /// [PlayerStatus.playing]. Returns `null` if fewer than two players remain.
  PairId? _formPairFromQueue() {
    if (_queue.length < 2) return null;
    final firstId = _queue.removeAt(0);
    final secondId = _queue.removeAt(0);
    final first = _roster[firstId.value];
    final pairId = pairIdBuilder(_pairSeq++);
    final pair = Pair(
      id: pairId,
      sessionId: state.session.id,
      playerOneId: firstId,
      playerTwoId: secondId,
      origin: PairOrigin.automatic,
      status: PairStatus.playing,
      queueOrder: _pairSeq,
    );
    _pairs[pairId.value] = pair;
    if (first != null) {
      _roster[firstId.value] = first.copyWith(status: PlayerStatus.playing);
    }
    final second = _roster[secondId.value];
    if (second != null) {
      _roster[secondId.value] = second.copyWith(status: PlayerStatus.playing);
    }
    return pairId;
  }

  void _setPairStatus(PairId pairId, PairStatus status) {
    final pair = _pairs[pairId.value];
    if (pair != null) {
      _pairs[pairId.value] = pair.copyWith(status: status);
    }
  }

  PairStatus _homeStatus(int level) =>
      level == _topLevel ? PairStatus.playing : PairStatus.waitingForUpperCourt;

  // --- Build -----------------------------------------------------------------

  RotationState build() {
    // Refresh derived court status from slot occupancy.
    final courts = state.courts.map((c) {
      final slot = _slots[c.id.value];
      final status = slot == null || slot.isEmpty
          ? CourtStatus.empty
          : slot.hasActiveMatch
          ? CourtStatus.occupied
          : CourtStatus.awaitingChallenger;
      return c.copyWith(status: status);
    }).toList();

    final next = RotationState(
      session: state.session,
      roster: _roster.values.toList(),
      queue: List.unmodifiable(_queue),
      courts: courts,
      pairs: _pairs.values.toList(),
      slots: _slots.values.toList(),
      matches: List.unmodifiable(_matches),
      history: [...state.history, ..._events],
    );

    // Defense in depth: the documented invariants must hold after every
    // transition. A violation is a rotation bug — fail loudly in debug/tests
    // rather than persist an inconsistent state.
    assert(
      next.hasUniqueActivePlayers,
      'Rotation produced a player active in two places: $next',
    );
    assert(
      next.hasNoDissolvedPairOnCourt,
      'Rotation left a dissolved pair on a court: $next',
    );

    return next;
  }
}
